version: '2'

services:

  dash:
    container_name: dash1
    restart: always
    build: ./dash1
    ports:
      - "8050:8050"
    command: gunicorn -w 1 -b :8050 app:server # was 8000
    # command: gunicorn --certfile=/etc/letsencrypt/csr/cert.crt --keyfile=/etc/letsencrypt/keys/nginx_ssl.key test:app
    # command: gunicorn --certfile=/etc/letsencrypt/csr/cert.crt --keyfile=/etc/letsencrypt/keys/nginx_ssl.key --bind 0.0.0.0:443 test:app


  nginx:
    container_name: nginx1
    restart: always
    build: ./nginx1
    ports:
      - "80:80"
      #- "443:443"
    depends_on:
      - dash1
